version: '3.5'

services:
  swos_web:
    container_name: swos_web
    build:
      context: ./docker
      dockerfile: Dockerfile_nginx
    volumes:
      - ./:/app/swos
    ports:
      - "8005:80"
    links:
      - swos_php
    depends_on:
      - swos_php
  swos_php:
    container_name: swos_php
    build:
      context: ./docker
      dockerfile: Dockerfile_php
    volumes:
      - ./:/app/swos

  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: 1212123
      POSTGRES_USER: pedrom
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  db-data:
  pgadmin_volume:
