version: '3.5'

services:
  swos_web:
    container_name: swos_web
    build:
      context: ./docker
      dockerfile: Dockerfile_nginx
    volumes:
      - ./:/app/swos
    ports:
      - "8005:80"
    links:
      - swos_php
    depends_on:
      - swos_php
  swos_php:
    container_name: swos_php
    build:
      context: ./docker
      dockerfile: Dockerfile_php
    volumes:
      - ./:/app/swos

  database:
    container_name: database
    image: mysql:${DATABASE_VERSION}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
