version: '3.5'

services:
  swos_web:
    container_name: swos_web
    build:
      context: ./docker
      dockerfile: Dockerfile_nginx
    volumes:
      - ./:/app/swos
    ports:
      - "8005:80"
    links:
      - swos_php
    depends_on:
      - swos_php
  swos_php:
    container_name: swos_php
    build:
      context: ./docker
      dockerfile: Dockerfile_php
    volumes:
      - ./:/app/swos

