parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Application\Team\Command\CreateTeamCommandHandler:
        public: true

    App\Domain\Team\TeamRepository: '@App\Infrastructure\Team\Repository\Doctrine\TeamRepository'
    App\Domain\Team\TypeRepository: '@App\Infrastructure\Team\Repository\Doctrine\TypeRepository'
    App\Domain\Common\CountryRepository: '@App\Infrastructure\Common\Repository\Doctrine\CountryRepository'

    App\Infrastructure\Team\Repository\InMemory\TeamRepository:
        public: true

    App\Infrastructure\Team\Repository\InMemory\TypeRepository:
        public: true

    App\Infrastructure\Common\Repository\InMemory\CountryRepository:
        public: true
